### ISSUE TITLE
Subset support

### ISSUE THREAD

**Issue by mitchellnw** [tmbdev/tarp#12]
Hello,

Does `tarp` currently support re-sharding with a subset of the data?

For instance, if I have `data/` which contains many tar files (lets say 100 tar files with 100 data in each file), and a binary string `subset.txt` which specifies which of these 100*100 data I want to keep, is it possible to use `tarp` to "re-shard" `data/` to get `newdata/`, also containing tar files with 100 data in each file, but only containing the data for which `subset.txt` indicates to include that data?

**Comment by mitchellnw** [comment]
Alternatively, would you recommend just specifying this subset in `webdataset`? Or would that incur too much of a slow-down?

**Comment by tmbdev** [comment]
Sorry for the late response. You can subset the data via "tarp cat --slice start:end:skip". So, you can partition the data into subsets by taking every 10th sample, for example, at different offsets.

It didn't really make sense to me to add anything more complex, since at that point, you might just write a little pipeline using WebDataset/TarWriter in Python. Tarp's main strength is in simple parallelization of simple operations.
