### ISSUE TITLE
Usage of shuffle in tarp

### ISSUE THREAD

**Issue by Griffintaur** [tmbdev/tarp#9]
I have a large tar file where data is sorted and now I want to shread into smaller tar files using tarp where data are shuffled across and within the smaller tar files.
`tarp cat --shuffle=5000 in.tar -o - | tarp split -c 10000 - -o ./out_-%06d.tar`
This command works but I want to understand how data is shuffled over across and within smaller tar files.

**Comment by tmbdev** [comment]
The data will be shuffled in a shuffle buffer of size 5000 and then split into shards of 10000. This means that most of the samples that were together in the original tar file will still be close together in the same shards in the output.  Since tarp does all processing sequentially, this is really all it can do.

You have two options:

- greatly increase the size of the shuffle buffer; make it 10x the size of the output shards and you'll get good mixing across shards
- first, split the original file into many small shards and then shuffle those shards and do a parallel cat with tarp from multiple shards simultaneously
